<?php
session_start();
require_once '../includes/config.php';
require_once '../includes/functions.php';
require_once '../includes/header.php';
require_once '../includes/footer.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: ../login.php?redirect=room-planner');
    exit();
}

// Get database connection
$db = new Database();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Planner - Prime Home Hub</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="../styles.css">
    <style>
        .planner-container {
            background: #f8f9fa;
            border-radius: 12px;
            padding: 20px;
            min-height: 600px;
        }
        .room-grid {
            display: grid;
            grid-template-columns: repeat(20, 30px);
            grid-template-rows: repeat(15, 30px);
            gap: 1px;
            background: #dee2e6;
            padding: 10px;
            border-radius: 8px;
            position: relative;
        }
        .grid-cell {
            background: white;
            border: 1px solid #f0f0f0;
            cursor: pointer;
            transition: all 0.3s ease;
        }
        .grid-cell:hover {
            background: #e3f2fd;
        }
        .grid-cell.wall {
            background: #495057;
        }
        .grid-cell.door {
            background: #8b4513;
        }
        .grid-cell.window {
            background: #87ceeb;
        }
        .grid-cell.furniture {
            background: #667eea;
        }
        .tools-panel {
            background: white;
            border-radius: 8px;
            padding: 15px;
        }
        .tool-btn {
            width: 100%;
            margin: 5px 0;
            padding: 10px;
            border: 2px solid #dee2e6;
            border-radius: 6px;
            background: white;
            cursor: pointer;
            transition: all 0.3s ease;
        }
        .tool-btn:hover {
            background: #667eea;
            color: white;
        }
        .tool-btn.active {
            background: #667eea;
            color: white;
        }
        .room-info {
            background: white;
            border-radius: 8px;
            padding: 15px;
            margin-top: 15px;
        }
    </style>
</head>
<body>
    <?php include '../includes/header.php'; ?>

    <!-- Page Header -->
    <section class="page-header bg-primary text-white py-5">
        <div class="container text-center">
            <h1 class="display-4 fw-bold">Room Planner</h1>
            <p class="lead">Design your room layout with precision</p>
        </div>
    </section>

    <!-- Planner Content -->
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="planner-container">
                        <h4 class="mb-3">Room Layout</h4>
                        <div class="room-grid" id="roomGrid">
                            <!-- Grid cells will be generated by JavaScript -->
                        </div>
                        
                        <div class="mt-3 d-flex gap-2">
                            <button class="btn btn-outline-danger" onclick="clearGrid()">
                                <i class="bi bi-trash"></i> Clear All
                            </button>
                            <button class="btn btn-outline-primary" onclick="savePlan()">
                                <i class="bi bi-save"></i> Save Plan
                            </button>
                            <button class="btn btn-outline-success" onclick="exportPlan()">
                                <i class="bi bi-download"></i> Export
                            </button>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-4">
                    <div class="tools-panel">
                        <h5 class="mb-3">Drawing Tools</h5>
                        
                        <button class="tool-btn active" data-tool="select" onclick="selectTool('select')">
                            <i class="bi bi-cursor"></i> Select
                        </button>
                        <button class="tool-btn" data-tool="wall" onclick="selectTool('wall')">
                            <i class="bi bi-square"></i> Wall
                        </button>
                        <button class="tool-btn" data-tool="door" onclick="selectTool('door')">
                            <i class="bi bi-door-open"></i> Door
                        </button>
                        <button class="tool-btn" data-tool="window" onclick="selectTool('window')">
                            <i class="bi bi-square"></i> Window
                        </button>
                        <button class="tool-btn" data-tool="furniture" onclick="selectTool('furniture')">
                            <i class="bi bi-square"></i> Furniture
                        </button>
                        <button class="tool-btn" data-tool="eraser" onclick="selectTool('eraser')">
                            <i class="bi bi-eraser"></i> Eraser
                        </button>
                    </div>
                    
                    <div class="room-info">
                        <h5 class="mb-3">Room Information</h5>
                        <div class="mb-3">
                            <label for="roomName" class="form-label">Room Name</label>
                            <input type="text" class="form-control" id="roomName" placeholder="Living Room">
                        </div>
                        <div class="mb-3">
                            <label for="roomDimensions" class="form-label">Dimensions (ft)</label>
                            <div class="row">
                                <div class="col-6">
                                    <input type="number" class="form-control" id="roomWidth" placeholder="Width" value="20">
                                </div>
                                <div class="col-6">
                                    <input type="number" class="form-control" id="roomHeight" placeholder="Height" value="15">
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="roomType" class="form-label">Room Type</label>
                            <select class="form-select" id="roomType">
                                <option value="living">Living Room</option>
                                <option value="bedroom">Bedroom</option>
                                <option value="kitchen">Kitchen</option>
                                <option value="bathroom">Bathroom</option>
                                <option value="office">Home Office</option>
                                <option value="dining">Dining Room</option>
                            </select>
                        </div>
                        
                        <div class="d-grid gap-2">
                            <button class="btn btn-outline-primary" onclick="loadTemplate()">
                                <i class="bi bi-collection"></i> Load Template
                            </button>
                            <button class="btn btn-outline-info" onclick="measureArea()">
                                <i class="bi bi-rulers"></i> Calculate Area
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Templates Modal -->
    <div class="modal fade" id="templatesModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Room Templates</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="list-group">
                        <button class="list-group-item list-group-item-action" onclick="loadTemplateData('living')">
                            <h6 class="mb-1">Living Room Template</h6>
                            <small class="text-muted">Standard living room layout with sofa and TV area</small>
                        </button>
                        <button class="list-group-item list-group-item-action" onclick="loadTemplateData('bedroom')">
                            <h6 class="mb-1">Bedroom Template</h6>
                            <small class="text-muted">Cozy bedroom with bed and wardrobe</small>
                        </button>
                        <button class="list-group-item list-group-item-action" onclick="loadTemplateData('kitchen')">
                            <h6 class="mb-1">Kitchen Template</h6>
                            <small class="text-muted">Functional kitchen with counter and appliances</small>
                        </button>
                        <button class="list-group-item list-group-item-action" onclick="loadTemplateData('office')">
                            <h6 class="mb-1">Home Office Template</h6>
                            <small class="text-muted">Productive workspace with desk and storage</small>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include '../includes/footer.php'; ?>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../js/navigation.js"></script>
    <script>
        let currentTool = 'select';
        let isDrawing = false;
        let gridData = [];
        
        // Initialize grid
        document.addEventListener('DOMContentLoaded', function() {
            initializeGrid();
        });
        
        function initializeGrid() {
            const grid = document.getElementById('roomGrid');
            grid.innerHTML = '';
            gridData = [];
            
            for (let i = 0; i < 300; i++) { // 20x15 = 300 cells
                const cell = document.createElement('div');
                cell.className = 'grid-cell';
                cell.dataset.index = i;
                cell.addEventListener('mousedown', startDrawing);
                cell.addEventListener('mouseenter', continueDrawing);
                cell.addEventListener('mouseup', stopDrawing);
                cell.addEventListener('click', placeElement);
                grid.appendChild(cell);
                gridData.push('empty');
            }
        }
        
        function selectTool(tool) {
            currentTool = tool;
            
            // Update button states
            document.querySelectorAll('.tool-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            document.querySelector(`[data-tool="${tool}"]`).classList.add('active');
        }
        
        function startDrawing(e) {
            if (currentTool === 'wall' || currentTool === 'door' || currentTool === 'window' || currentTool === 'furniture') {
                isDrawing = true;
                applyTool(e.target);
            }
        }
        
        function continueDrawing(e) {
            if (isDrawing) {
                applyTool(e.target);
            }
        }
        
        function stopDrawing() {
            isDrawing = false;
        }
        
        function placeElement(e) {
            if (currentTool === 'select' || currentTool === 'eraser') {
                applyTool(e.target);
            }
        }
        
        function applyTool(cell) {
            const index = parseInt(cell.dataset.index);
            
            switch (currentTool) {
                case 'wall':
                    cell.className = 'grid-cell wall';
                    gridData[index] = 'wall';
                    break;
                case 'door':
                    cell.className = 'grid-cell door';
                    gridData[index] = 'door';
                    break;
                case 'window':
                    cell.className = 'grid-cell window';
                    gridData[index] = 'window';
                    break;
                case 'furniture':
                    cell.className = 'grid-cell furniture';
                    gridData[index] = 'furniture';
                    break;
                case 'eraser':
                    cell.className = 'grid-cell';
                    gridData[index] = 'empty';
                    break;
            }
        }
        
        function clearGrid() {
            if (confirm('Are you sure you want to clear the entire grid?')) {
                initializeGrid();
            }
        }
        
        function savePlan() {
            const roomName = document.getElementById('roomName').value || 'Untitled Room';
            const roomType = document.getElementById('roomType').value;
            
            const planData = {
                name: roomName,
                type: roomType,
                grid: gridData,
                timestamp: new Date().toISOString()
            };
            
            // In a real application, this would save to the database
            console.log('Saving room plan:', planData);
            localStorage.setItem('roomPlan', JSON.stringify(planData));
            alert('Room plan saved successfully!');
        }
        
        function exportPlan() {
            const roomName = document.getElementById('roomName').value || 'room-plan';
            
            // Create a simple text representation
            let exportText = `Room: ${roomName}\n`;
            exportText += `Type: ${document.getElementById('roomType').value}\n`;
            exportText += `Dimensions: ${document.getElementById('roomWidth').value}x${document.getElementById('roomHeight').value} ft\n\n`;
            exportText += 'Grid Layout:\n';
            
            for (let i = 0; i < gridData.length; i++) {
                if (i % 20 === 0) exportText += '\n';
                exportText += gridData[i].charAt(0).toUpperCase() + ' ';
            }
            
            // Download as text file
            const blob = new Blob([exportText], { type: 'text/plain' });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${roomName}.txt`;
            a.click();
            window.URL.revokeObjectURL(url);
        }
        
        function loadTemplate() {
            const modal = new bootstrap.Modal(document.getElementById('templatesModal'));
            modal.show();
        }
        
        function loadTemplateData(templateType) {
            // Clear grid first
            initializeGrid();
            
            // Apply template based on type
            const templates = {
                living: function() {
                    // Add walls around perimeter
                    for (let i = 0; i < 20; i++) {
                        applyToolByIndex(i, 'wall'); // Top wall
                        applyToolByIndex(i + 280, 'wall'); // Bottom wall
                    }
                    for (let i = 0; i < 15; i++) {
                        applyToolByIndex(i * 20, 'wall'); // Left wall
                        applyToolByIndex(i * 20 + 19, 'wall'); // Right wall
                    }
                    // Add door
                    applyToolByIndex(59, 'door');
                    applyToolByIndex(79, 'door');
                    // Add windows
                    applyToolByIndex(2, 'window');
                    applyToolByIndex(3, 'window');
                    applyToolByIndex(16, 'window');
                    applyToolByIndex(17, 'window');
                },
                bedroom: function() {
                    // Similar template logic for bedroom
                    for (let i = 0; i < 20; i++) {
                        applyToolByIndex(i, 'wall');
                        applyToolByIndex(i + 280, 'wall');
                    }
                    for (let i = 0; i < 15; i++) {
                        applyToolByIndex(i * 20, 'wall');
                        applyToolByIndex(i * 20 + 19, 'wall');
                    }
                    applyToolByIndex(39, 'door');
                    applyToolByIndex(59, 'door');
                }
            };
            
            if (templates[templateType]) {
                templates[templateType]();
            }
            
            // Close modal
            bootstrap.Modal.getInstance(document.getElementById('templatesModal')).hide();
        }
        
        function applyToolByIndex(index, tool) {
            const cell = document.querySelector(`[data-index="${index}"]`);
            if (cell) {
                const oldTool = currentTool;
                currentTool = tool;
                applyTool(cell);
                currentTool = oldTool;
            }
        }
        
        function measureArea() {
            const width = parseInt(document.getElementById('roomWidth').value) || 20;
            const height = parseInt(document.getElementById('roomHeight').value) || 15;
            const area = width * height;
            
            alert(`Room Area: ${area} square feet\n${area * 0.093} square meters`);
        }
    </script>
</body>
</html>
